-- 1
SELECT ENAME , JOB , SAL 
FROM EMP e JOIN DEPT d ON e.DEPTNO = d.DEPTNO 
WHERE d.LOC = 'chicago';

-- 2
SELECT m.EMPNO , m.ENAME , m.JOB , m.DEPTNO 
FROM EMP e RIGHT JOIN EMP m ON e.MGR = m.EMPNO 
WHERE e.EMPNO IS NULL;

-- 3
SELECT e.ename, e.JOB , e.MGR 
FROM EMP e JOIN EMP e2 ON e.MGR = e2.EMPNO 
WHERE e2.ENAME = 'blake';


-- 4
SELECT *
FROM EMP e
ORDER BY HIREDATE
LIMIT 5;


-- 5
SELECT e.ENAME , e.JOB , e.DEPTNO
FROM EMP e JOIN EMP e2 ON e.MGR = e2.EMPNO 
WHERE e2.ENAME = 'jones';